name: Waffle Hub gpu test on self-hosted runner

on:
  pull_request:
    branches: ["*"]

jobs:
  Tests:
    timeout-minutes: 60
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9']
        pytorch-version: [
          'torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117',
          'torch==2.0.0+cu117 torchvision==0.15.1+cu117 --index-url https://download.pytorch.org/whl/cu117',
          'torch==2.0.1+cu117 torchvision==0.15.2+cu117 --index-url https://download.pytorch.org/whl/cu117'
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip wheel
          pip install ${{ matrix.pytorch-version }}
          pip install -r requirements.txt
          pip install pytest
          pip install tensorrt==8.6.1
        shell: bash  # for Windows compatibility
      - name: Check environment
        run: |
          python --version
          pip --version
          pip list
      - name: Pytest tests
        shell: bash  # for Windows compatibility
        run: python -m pytest tests/test_gpu.py -v
